### ISSUE TITLE
Please make a v0.12.2 release

### ISSUE THREAD

**Issue by kpreid** [Drakulix/simplelog.rs#141]
This release would include #131, #132, and #139 if made from `master` now. I need #131 to be able to continue using `simplelog::TermLogger` without a fatal `termcolor` version conflict.

**Comment by AdrianEddy** [comment]
+1 I need this too

**Comment by gzz2000** [comment]
+1 Need this too. For me the case is I need the `TestLogger`.

**Comment by juffson** [comment]
+1 Need this too

**Comment by TicClick** [comment]
@Drakulix I understand you may have a lot going on right now, but could you please look into pushing out a release? more and more crates (such as `egui`, for instance) bump their `termcolor` dependency, directly or not, which makes them incompatible with `simplelog` due to https://github.com/Drakulix/simplelog.rs/issues/147

**Comment by Drakulix** [comment]
https://github.com/Drakulix/simplelog.rs/actions/runs/8139587980/job/22243162121 should be done
