### ISSUE TITLE
Setting config thread level to 'Off' enables all levels

### ISSUE THREAD

**Issue by spearman** [Drakulix/simplelog.rs#43]
I think there is something wrong with the level comparison in the new config. Previously I would set thread to 'None' to disable logging the thread number for all levels. Setting it to 'Off' with the config builder seems to enable it for all levels

**Comment by Drakulix** [comment]
As yes, this arises from a kinda wrong usage off `LevelFilter` in my code.

Usually `LevelFilter` is used to declare a maximum filter up to `Trace`, but I am using it the other way around (with `Error` being the maximum) because simplelog gets more verbose on more verbose levels. This results in `Off` being ordered wrong for this usecase.

v0.7.1 is released and contains a workaround, so it works as expected.
Fixed by e39f088a5cb75a90b12e0012278a719dd40c01c2
