### ISSUE TITLE
Default padding changed

### ISSUE THREAD

**Issue by SirWindfield** [Drakulix/simplelog.rs#48]
I've used `simplelog@0.4.0` and after bumping to the newest version, my logging levels get padded by default. Is this an intended change?

**Comment by Drakulix** [comment]
- `0.6.0` introduced padding (one reason, it was a major version bump).
- Since `0.7.0` padding is configurable and can also be disabled again.

Defaults are open to discussion, but I have not created an issue yet.
You are not the first one to bring this up (see #44), but I did not want to bump the version again, just for changing the default padding.

**Comment by SirWindfield** [comment]
Unterstandable. I used the config builder to circumvent it :) thanks for the heads up.

**Comment by evitalis** [comment]
@SirWindfield What padding option do you think would make a sensible default? I am thinking the padding being on the right, but interested in the opinions/rationale of others.

**Comment by SirWindfield** [comment]
Right makes the most sense since English is read left to right.

**Comment by flaviojs** [comment]
Both left padding and right padding defaults are guaranteed to have people for it and against it.

A consensus is impossible (like most coding style discussions) so I think the default should be either:
1. no padding (those who care will configure according to their preference)
2. or whatever the author prefers

Personally I prefer left padding because I think the message text is the main content.
Left padding guides my eye to the start of the message text automatically, right padding does not.

**Comment by SirWindfield** [comment]
> Both left padding and right padding defaults are guaranteed to have people for it and against it.

That's actually the best answer here to be honest.

**Comment by evitalis** [comment]
With that in mind then the best course of action may just be to leave out the default pad all together and let people set what they prefer. Seems to be the best middle ground.

**Comment by Drakulix** [comment]
v0.8.0 now defaults to no-padding.
Just set it to whatever variant you prefer, if you want padding.
This seems to be the only sensible default and I have no interesting in debating this further.
I think all points have been made and this shall be my final decision.
