### ISSUE TITLE
Wrong time?

### ISSUE THREAD

**Issue by Hultan** [Drakulix/simplelog.rs#51]
I am using :
  simplelog = "^0.7.3"
and I am getting utc(?) time in the log file. My local time (Sweden) is currently +2 hours, so every log entry in the log file is two hours off. Is this by design, or is it something that I have failed to set up correctly?

**Comment by Drakulix** [comment]
> I am using :
> simplelog = "^0.7.3"
> and I am getting utc(?) time in the log file. My local time (Sweden) is currently +2 hours, so every log entry in the log file is two hours off. Is this by design, or is it something that I have failed to set up correctly?

UTC as default is by design (and usually used on servers and a like), but you can use your local timzone by configuring your logger(s).

Either set a fixed offset using [ConfigBuilder::set_time_offset](https://docs.rs/simplelog/0.7.4/simplelog/struct.ConfigBuilder.html#method.set_time_offset) or default to the local timezone (which will also take care of daylight savings and the like) by using [ConfigBuilder::set_time_to_local](https://docs.rs/simplelog/0.7.4/simplelog/struct.ConfigBuilder.html#method.set_time_to_local).

**Comment by Hultan** [comment]
Awesome, I had a feeling I had missed something. Thanks for this crate!
